# Generated by Django 3.0.4 on 2022-09-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('seudonimo', models.CharField(blank=True, max_length=50, verbose_name='seudonimo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
