# Generated by Django 3.2.14 on 2022-08-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
